### ISSUE TITLE
Any article about this research?

### ISSUE THREAD

**Issue by finardi** [yuanbit/fiqa#2]
Have you some article about this repo? The code and stratategy to tackle this problem appers very ok! 

Thank you for your sharing the weights and code.

**Comment by finardi** [comment]
Hi again @yuanbit! I saw the notebook for one epoch in colab took ~4h. If I cut the tsv files (if the purpose to speedup/study): 
```
FiQA_train_question_final (e.g. cut the data to only  100 questions)
FiQA_train_doc_final (e.g. cut the data to only  2000 docs)
FiQA_train_question_doc_final (e.g. cut the data to have all relevant qid docid in above)
```
Do I need redo the Lucene Index in retrieval folder? 
I never had contact with this index, and I'm a little lost on how to proceed. 

Your code on the subject is one of the best I've seen, very well organized and commented, congrats!

**Comment by yuanbit** [comment]
Hi @finardi! Thank you for your comments! This repo is based on my master's thesis and I am working to publish a short paper now. I could add my thesis to the repo, though it is quite lengthy.

For the purpose of speeding the training step up, I would recommend the following:

1. The easiest way is to change the config in the notebook. If you reduce the max_seq_len and increase the batch_size then then it would be much faster. E.g. max_seq_len of 128 and batch_size of 64. You can play around with these two hyperparameters.
```
config = {'bert_model_name': 'bert-qa',
          'max_seq_len': 512,
          'batch_size': 16,
          'learning_rate': 3e-6,
          'weight_decay': 0.01,
          'n_epochs': 2,
          'num_warmup_steps': 10000}
```

2. Another thing to try without redoing the Lucene index is to reduce the number of candidate answers for each question. You could try for example, 20 candidate answers for each question. You would need to pull the docker image and run: 
```
python3 src/generate_data.py --query_path data/raw/FiQA_train_question_final.tsv \
                             --label_path data/raw/FiQA_train_question_doc_final.tsv\
                            --cands_size CANDS_SIZE --output_dir OUTPUT_DIR
```

Good luck!

**Comment by yuanbit** [comment]
The link to my thesis is now added to README: [FinBERT-QA: Financial Question Answering with pre-trained BERT Language Models](https://drive.google.com/file/d/1UyB9Ch9H1WnxW4WQgGWEoB-tAV1FMsf9/view?usp=sharing)
